spring:
  application:
    name: ticket-booking-backend
  mail:
    host: smtp.gmail.com
    port: 587
    username: ekdvsampath02@gmail.com
    password: wonhlwvpvzgrijuz
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

  data:
    mongodb:
      uri: ${MONGO_URI}
      write-concern: ACKNOWLEDGED

server:
  port: 8080

jwt:
  secret: "THIS_IS_A_VERY_LONG_SECRET_KEY_AT_LEAST_64_CHARACTERS_LONG_FOR_HS512"
  expiration: 3600000

cloudinary:
  cloud-name: ${CLOUDINARY_CLOUD_NAME}
  api-key: ${CLOUDINARY_API_KEY}
  api-secret: ${CLOUDINARY_API_SECRET}

payhere:
  merchant:
    id: ${MERCHANT_ID}
    secret: ${MERCHANT_SECRET}

dotenv:
  ignoreIfMissing: false

qr:
  secret: ${QR_SECRET}

logging:
  level:
    org.springframework.data.mongodb: INFO