spring:
  application:
    name: ticket-booking-backend

  servlet:
    multipart:
      max-file-size: 25MB
      max-request-size: 25MB

  data:
    mongodb:
      uri: ${MONGO_URI}
      write-concern: ACKNOWLEDGED

server:
  port: ${PORT:10000}
  address: 0.0.0.0

jwt:
  secret: ${JWT_SECRET}
  expiration: 3600000

cloudinary:
  cloud-name: ${CLOUDINARY_CLOUD_NAME}
  api-key: ${CLOUDINARY_API_KEY}
  api-secret: ${CLOUDINARY_API_SECRET}

payhere:
  merchant:
    id: ${MERCHANT_ID}
    secret: ${MERCHANT_SECRET}

dotenv:
  ignoreIfMissing: true

qr:
  secret: ${QR_SECRET}

resend:
  api:
    key: ${RESEND_API_KEY}

logging:
  level:
    org.springframework.data.mongodb: INFO